package com.order;

import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path = "/orders")
public class HealthCheckController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TestRepository testRepository;

	@GetMapping(path = "/healthcheck")
	public @ResponseBody String GetHealth() {
		return "health ok";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<test> GetTests() {
		return testRepository.findAll();
	}

	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addTest() {

		test testEntity = new test();
		Random random = new Random();
		testEntity.setTestId(random.nextInt());
		testEntity.setName("newname");
		testRepository.save(testEntity);
		return "Saved";
	}

}